spring:
  server:
    max-http-header-size: 20000
  datasource:
    url: jdbc:postgresql://172.19.0.2:5432/freitagsmarkt_db
    username: root
    password: rootpass
#    driver-class-name: org.hibernate.dialect.PostgreSQLDialect

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create-drop
        enable_lazy_load_no_trans: true
    generate-ddl: true

management:
  endpoints:
    web:
      exposure:
        include: httptrace
logging:
  level:
    root: INFO
    auto.freitagsmarkt: DEBUG
    org:
      springframework:
        web: DEBUG
  pattern:
    console: "%d{yyyy-dd-MM HH:mm:ss} - %msg%n"