spring:
  server:
    max-http-header-size: 20000
  datasource:
    url: jdbc:postgresql://172.19.0.2:5432/freitagsmarkt_db
    username: root
    password: rootpass
#    driver-class-name: org.hibernate.dialect.PostgreSQLDialect

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
    generate-ddl: true
  graphql:
    graphiql:
      enabled: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: INFO
    auto.cc.info: DEBUG
  pattern:
    console: "%d{yyyy-dd-MM HH:mm:ss} - %msg%n"