spring:
  server:
    max-http-header-size: 20000
  datasource:
    url: jdbc:mysql://172.22.0.3:3306/freitagsmarkt_db
    username: root
    password: rootpassword
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        ddl-auto: update
    generate-ddl: true
  graphql:
    graphiql:
      enabled: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379